### ISSUE TITLE
Sample code in readme not working

### ISSUE THREAD

**Issue by jarmmar** [Uelb/pinch-ruby#3]
The sample codes on how to set authentication do not work:

```
⇒ gem install pinch
Successfully installed pinch-0.3.3
Parsing documentation for pinch-0.3.3
Done installing documentation for pinch after 0 seconds
1 gem installed
⇒ vim first.rb
⇒ ruby first.rb 
first.rb:3:in `<main>': uninitialized constant Pinch::Configuration (NameError)
⇒ ruby -v
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]
⇒ vim second.rb
⇒ ruby second.rb 
second.rb:2:in `<main>': uninitialized constant Pinch::PinchClient (NameError)
```

Has the code been tested??

Sample codes from readme:

```
# config/initializers/pinch.rb
require 'pinch'
Pinch::Configuration.x_api_token = 'MY_API_KEY'
# or the recommended way
Pinch::Configuration.x_api_token = ENV['PINCH_API_KEY']
```

```
require 'pinch'
pinch = Pinch::PinchClient.new(x_api_token: "MY_API_KEY", x_api_email: "myemail@example.com")
```

**Comment by Uelb** [comment]
The gem to install is pinch-api. But this gem can only be used by https://github.com/Inchdev/ clients.

**Comment by jarmmar** [comment]
Tried `gem install pinch-api` earlier (which's successful) but got the same result above.

**Comment by Uelb** [comment]
Well, I need further details to debug, but who are you ? And what are you trying to do ?

**Comment by jarmmar** [comment]
I stumbled upon https://github.com/Inchdev/pinch-ruby/ and found the gem was automatically generated by APIMATIC (which seems a pretty interesting idea).

Then gave it a try but got the error. It would have been better if the sample code really works (without compilation error)

Feel free to ignore this (maybe I shouldn't have reported this issue to begin with).
